---

- hosts: localhost

  tasks:
    - name: Apt Autoremove
      shell: yes | apt-get autoremove
      become: true
    
    - name: Apt Install
      shell: yes | apt-get -y -f install
      become: true
    
    - name: Apt Upgrade
      shell: apt update && apt upgrade -y
      become: true
    
    - name: Configure DPKG
      shell: dpkg --configure -a
      become: true

    - name: Add Software Repository Add On
      shell: apt-get install -y software-properties-common
      become: true

    - name: Add Apt-Repository
      shell: add-apt-repository ppa:graphics-drivers/ppa
      become: true
    
    - name: Apt Get Update
      shell: yes | apt-get update
      become: true
    
    - name: Apt Search
      shell: apt search nvidia-driver
      become: true
    
    - name: Install Nvidia Drivers
      shell: apt install -y nvidia-driver-525
      become: true 

# distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
#       && curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
#       && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | \
#             sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
#             sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

# sudo apt-get update

# sudo apt-get install -y nvidia-docker2

# sudo systemctl restart docker


# sudo docker run --gpus all --entrypoint=/bin/bash -it nvidia/cuda:11.6.2-base-ubuntu20.04