---

- hosts: all

  tasks:
    - name: Install Curl
      shell: apt update && apt install -y curl
      become: true

    - name: Install Conda
      block:

        - name: Download Miniconda
          get_url:
            url: https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh
            dest: /tmp/install-miniconda.sh
            checksum: md5:9dea0dd8a73cbb2801c4bc9d225f1ad0
            mode: 0550

        - name: Create conda folder
          become: True
          file:
            path: /home/master/miniconda3
            state: directory
            owner: master
            mode: 755
            recurse: yes

        - name: Run the installer
          shell: /tmp/install-miniconda.sh -b -u -f -p /home/master/miniconda3
          ignore_errors: true

        - name: Remove the installer
          file:
            state: absent
            path: /tmp/install-miniconda.sh

        - name: Add miniconda bin to path
          become: True
          shell: echo 'export PATH=/home/master/miniconda3/bin:$PATH' >> /etc/profile

        - name: conda - read permission for all
          become: True
          file:
            path: /home/master/miniconda3
            mode: +r
            recurse: yes

        - name: conda - execution permission for all
          become: True
          file:
            path: /home/master/miniconda3/bin
            mode: +x
            recurse: yes
        
        - name: conda - write permission for all
          become: True
          file:
            path: /home/master/miniconda3
            mode: +w
            recurse: yes


    - name: Install DS Toolkit, CUDA, CUDNN, Tensorflow GPU, PyTorch GPU, JupyterLab and Code Server
      shell: . /home/master/miniconda3/bin/activate && yes | mamba install cudatoolkit cudnn numpy pandas scikit-learn matplotlib seaborn pillow beautifulsoup4 scrapy nltk scipy tensorflow-gpu pytorch torchvision jupyterlab code-server
      become: true
      ignore_errors: true

    - name: Export Config
      shell: . /home/master/miniconda3/bin/activate && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/
      become: true
    
    - name: Export CONDA PREFIX Variable
      shell: . /home/master/miniconda3/bin/activate && mkdir -p $CONDA_PREFIX/etc/conda/activate.d
      become: true
    
    - name: Export Library Path
      shell: . /home/master/miniconda3/bin/activate && echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/' > $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh
      become: true